import type { Theme } from './types';

// 精选 10 套主题：经典 + 潮流 + Ez 生态

export const builtinThemes: Theme[] = [
  // === Ez 生态统一主题（默认） ===
  {
    id: 'ez-lemon',
    name: '柠檬黄',
    description: 'Ez 系列统一风格，温暖活力',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1e293b !important; background-color: #fefce8 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #1e293b !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #1e293b !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #1e293b !important;',
      strong: 'font-weight: 700; color: #000 !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #ca8a04 !important; text-decoration: none; border-bottom: 1px solid #eab308; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #1e293b !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fef9c3 !important; border-left: 4px solid #eab308; color: #555 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f1f5f9 !important; color: #dc2626 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1e293b !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fef9c3 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1e293b !important; border: 1px solid #e2e8f0;',
      td: 'padding: 12px 16px; border: 1px solid #e2e8f0; color: #1e293b !important;',
      tr: 'border: none;',
    }
  },

  // === 经典类 ===
  {
    id: 'apple',
    name: 'Mac',
    description: '纯净现代的极致留白',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1d1d1f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #1d1d1f !important;',
      strong: 'font-weight: 700; color: #000 !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #1d1d1f !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f5f5f7 !important; border-left: 4px solid #0066cc; color: #555 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f7 !important; color: #0066cc !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f7 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1d1d1f !important; border: 1px solid #e0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #e0e0e0; color: #1d1d1f !important;',
      tr: 'border: none;',
    }
  },

  {
    id: 'claude',
    name: 'Claude',
    description: '温润的燕麦卡其色底',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2b2b2b !important; background-color: #f8f6f0 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #b75c3d !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #b75c3d !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #2b2b2b !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #2b2b2b !important;',
      strong: 'font-weight: 700; color: #b75c3d !important; background-color: rgba(183,92,61,0.08); padding:0 4px; border-radius:4px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #b75c3d !important; text-decoration: none; border-bottom: 1px solid #b75c3d; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #2b2b2b !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: rgba(183, 92, 61, 0.04) !important; border-left: 4px solid #b75c3d; color: #555 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0ece4 !important; color: #b75c3d !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0ece4 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0ece4 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2b2b2b !important; border: 1px solid #e0ddd6;',
      td: 'padding: 12px 16px; border: 1px solid #e0ddd6; color: #2b2b2b !important;',
      tr: 'border: none;',
    }
  },

  {
    id: 'linear',
    name: 'Linear',
    description: '纯正的暗夜赛博极客风',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f1f1f2 !important; background-color: #101114 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #f1f1f2 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #f1f1f2 !important;',
      strong: 'font-weight: 700; color: #fff !important;',
      em: 'font-style: italic; color: #bbb !important;',
      a: 'color: #5e6ad2 !important; text-decoration: none; border-bottom: 1px solid #5e6ad2; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #f1f1f2 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #1a1a1a !important; border-left: 4px solid #5e6ad2; color: #ccc !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #1a1a2e !important; color: #5e6ad2 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1a1a2e !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #1a1a2e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #f1f1f2 !important; border: 1px solid #333;',
      td: 'padding: 12px 16px; border: 1px solid #333; color: #f1f1f2 !important;',
      tr: 'border: none;',
    }
  },

  // === 潮流类 ===
  {
    id: 'notion',
    name: 'Notion',
    description: '极致克制的黑白灰',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;',
      h2: 'font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;',
      h3: 'font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;',
      h4: 'font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;',
      p: 'margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;',
      strong: 'font-weight: 700; color: #37352f !important;',
      em: 'font-style: italic; color: #37352f !important;',
      a: 'color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);',
      ul: 'margin: 4px 0; padding-left: 26px;',
      ol: 'margin: 4px 0; padding-left: 26px;',
      li: 'margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;',
      blockquote: 'margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;',
      hr: 'margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;',
      td: 'padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;',
      tr: 'border: none;',
    }
  },

  {
    id: 'github',
    name: 'GitHub',
    description: '开发者最熟悉的阅读界面',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #1f2328 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 1px solid #d1d9e0;',
      h2: 'font-size: 24px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #d1d9e0;',
      h3: 'font-size: 20px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;',
      h4: 'font-size: 16px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;',
      p: 'margin: 16px 0 !important; line-height: 1.6 !important; color: #1f2328 !important;',
      strong: 'font-weight: 600; color: #1f2328 !important;',
      em: 'font-style: italic; color: #1f2328 !important;',
      a: 'color: #0969da !important; text-decoration: underline; text-underline-offset: 2px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 4px 0; line-height: 1.6 !important; color: #1f2328 !important;',
      blockquote: 'margin: 16px 0; padding: 8px 16px; background-color: transparent !important; border-left: 4px solid #d0d7de; color: #656d76 !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, "Liberation Mono", Menlo, monospace; padding: 3px 6px; background-color: rgba(175,184,193,0.2) !important; color: #1f2328 !important; border-radius: 6px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 16px; background-color: #f6f8fa !important; border-radius: 6px; overflow-x: auto; font-size: 13px !important; line-height: 1.45 !important;',
      hr: 'margin: 24px auto; border: none; height: 3px; background-color: #d1d9e0 !important; width: 100%; border-radius: 2px;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f6f8fa !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1f2328 !important; border: 1px solid #d1d9e0;',
      td: 'padding: 8px 16px; border: 1px solid #d1d9e0; color: #1f2328 !important;',
      tr: 'border: none;',
    }
  },

  {
    id: 'dracula',
    name: 'Dracula',
    description: '暗紫色赛博吸血鬼美学',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;',
      strong: 'font-weight: 700; color: #ffb86c !important;',
      em: 'font-style: italic; color: #8be9fd !important;',
      a: 'color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;',
      td: 'padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;',
      tr: 'border: none;',
    }
  },

  {
    id: 'nord',
    name: 'Nord',
    description: '北欧极地冰霜蓝',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #d8dee9 !important; background-color: #2e3440 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #88c0d0 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #81a1c1 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #88c0d0 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #d8dee9 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #d8dee9 !important;',
      strong: 'font-weight: 700; color: #eceff4 !important;',
      em: 'font-style: italic; color: #a3be8c !important;',
      a: 'color: #88c0d0 !important; text-decoration: none; border-bottom: 1px solid #88c0d0; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #d8dee9 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #3b4252 !important; border-left: 4px solid #5e81ac; color: #d8dee9 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #3b4252 !important; color: #a3be8c !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #3b4252 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #4c566a !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #3b4252 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #88c0d0 !important; border: 1px solid #4c566a;',
      td: 'padding: 12px 16px; border: 1px solid #4c566a; color: #d8dee9 !important;',
      tr: 'border: none;',
    }
  },
];

// 主题分组
export const THEME_GROUPS = [
  { label: 'Ez 生态', themes: builtinThemes.filter(t => t.id === 'ez-lemon') },
  { label: '经典', themes: builtinThemes.filter(t => ['apple', 'claude', 'linear'].includes(t.id)) },
  { label: '潮流', themes: builtinThemes.filter(t => ['notion', 'github', 'dracula', 'nord'].includes(t.id)) },
];

export { builtinThemes as THEMES };
